import React from "react";
import Layout from "./Layout";
import { Box } from "@mui/material";
import styles from "../styles/terms.module.css";

const TermsAndConditions = () => {
  return (
    <Layout>
      <Box className={styles.main} sx={{ margin: "4em 12%" }}>
        <h2 className={styles.title}>Terms & Conditions</h2>
        <h3 className={styles.subTitle}>Service and Contract Information</h3>
        <p className={styles.paragraph}>
          CCLIMO.AE PASSENGERS TRANSPORT BY LUXURY VEHICLES COMPANY. THE
          CONTRACT (FINAL AGREEMENT) FOR THE PROVISION OF THE TRANSPORT SERVICE
          IS BETWEEN YOU (THE CLIENT), AND THE THIRD-PARTY SERVICE PROVIDER,
          FROM NOW ON TERMED AS YOUR DRIVER. BY BOOKING A SERVICE ON OUR
          WEBSITE, YOU ARE ENTERING INTO A CONTRACT WITH THE DRIVER.
          RESERVATIONS AT CCLIMO.AE ARE SUBJECT TO THE AVAILABILITY OF THE
          TRANSFER COMPANIES AND APPROPRIATE VEHICLES.
        </p>
        <h3 className={styles.subTitle}>TRAVEL DETAILS</h3>
        <p className={styles.paragraph}>
          FOR TRANSFERS FROM THE AIRPORT, THE DRIVER WILL TAKE THE INITIAL
          PLANNED TIME OF ARRIVAL OF YOUR FLIGHT (SUBMITTED DURING THE BOOKING
          BY CLIENT) AS A REFERENCE FOR THE PICK-UP TIME OF THE CLIENT. THE
          LOCAL AVERAGE TIME TO COLLECT CHECKED-IN LUGGAGE AND GET THROUGH
          CUSTOMS WILL BE ADDED TO THE INITIAL PLANNED TIME OF ARRIVAL, I.E.
          TIME OF ARRIVAL OF THE PLANE IS NOT EQUAL TO THE TIME THE CLIENT WILL
          BE PICKED UP BY THE DRIVER. COMPARE YOUR BOOKING DETAILS WITH THE
          CONFIRMATION RECEIPT OF YOUR DRIVER. EVENTUAL CHANGES (ALL CHANGES,
          INCLUDING FLIGHT DELAYS) OR DISCREPANCIES NEED TO BE REPORTED DIRECTLY
          TO YOUR DRIVER VIA OUR SYSTEM (TO MANAGE AT OUR WEBSITE IN ‘YOUR
          BOOKINGS’ PAGE). ANY ADJUSTMENTS TO YOUR FLIGHT WILL BE TAKEN INTO
          CONSIDERATION BUT COULD RESULT IN POSSIBLE WAITING TIMES. WE ADVISE
          THE CLIENT TO CONTACT THE DRIVER IF THE DELAY IS MORE THAN 1 HOUR.
        </p>
        <h3 className={styles.subTitle}>LIABILITY</h3>
        <p className={styles.paragraph}>
          THE LIABILITY FOR THE PROVISION OF TRANSFER SERVICES BETWEEN YOU AND
          THE DRIVER IS RESTRICTED SOLELY TO THOSE TWO PARTIES BETWEEN WHOM THE
          SERVICE HAS BEEN CONTRACTED. CCLIMO.AE LIABILITIES RESULTING FROM THIS
          AGREEMENT SHALL, THEREFORE, BE LIMITED TO THOSE OF A THIRD-PARTY
          BROKER BETWEEN YOU AND THE DRIVER. ANY LIABILITIES RESULTING FROM THE
          PROVISION OF THE TRANSFER SERVICE SHALL BE THE SOLE RESPONSIBILITY OF
          THE DRIVER AND THEIR INSURANCE COMPANIES. CCLIMO.AE AND/OR THE DRIVER
          IS NOT LIABLE FOR DAMAGES RESULTING FROM DELAYS, INCLUDING DELAYS
          CAUSED BY WAITING TIME ON THE AIRPORT, INCLUDING DAMAGES CAUSED BY
          MISSING ANY POSSIBLE TRANSFERS AND CONNECTIONS, INCLUDING CONNECTING
          FLIGHTS, IF AND TO THE EXTENT THAT CCLIMO.AE AND/OR DRIVER
          DEMONSTRATES THAT SHE OR HER EMPLOYEES TOOK REASONABLE MEASURES TO
          PREVENT THE DAMAGES, OR IF AND TO THE EXTENT IT WAS NOT POSSIBLE FOR
          CCLIMO.AE AND/OR DRIVER AND HER EMPLOYEES TO TAKE MEASURES TO TAKE
          SUCH MEASURES. IN AGREEING TO THE TERMS AND CONDITIONS, YOU ACCEPT
          THAT CCLIMO.AE WILL IN NO WAY BE HELD RESPONSIBLE FOR ANY LOSSES,
          EXPENSES OR CLAIMS MADE BY YOU IN THE EVENT OF ANY PROBLEM ASSOCIATED
          WITH THE TRANSFER AND ALL CLAIMS WILL BE REDIRECTED TO THE DRIVER.
          CCLIMO.AE WILL, HOWEVER, USE ALL REASONABLE EFFORTS TO ASSIST THE USER
          IN SOLVING ANY ISSUES OR COMPLAINTS.
        </p>
        <h3 className={styles.subTitle}>AVAILABILITY OF SERVICES</h3>
        <p className={styles.paragraph}>
          CCLIMO.AE IS ENTITLED, ON BEHALF OF THE DRIVER, TO REFUSE ANY ORDER
          PLACED BY YOU. WE DO NOT GUARANTEE TO SUCCESSFULLY ALLOCATE A DRIVER
          TO EVERY BOOKING REQUEST. ALL INFORMATION GIVEN ON THE WEBSITES IS IN
          GOOD FAITH AND IS BELIEVED TO BE CORRECT AT THE TIME OF PRINT.
          CCLIMO.AE WILL NOT BE RESPONSIBLE FOR ANY OTHER INACCURACIES DUE TO
          OUT OF DATE INFORMATION WHICH MAY HAVE NOT BEEN POINTED OUT TO US BY
          THE DRIVER.
        </p>
        <h3 className={styles.subTitle}>TRANSPORT SERVICE</h3>
        <p className={styles.paragraph}>
          THE ROUTE TO OR FROM THE DESTINATION CANNOT BE GUARANTEED AND THE
          GOOGLE MAP DISPLAYED ON OUR WEBSITE IS SOLELY FOR INFORMATIONAL
          PURPOSES. WHILST REASONABLE EFFORT IS MADE TO ENSURE THAT PICKUP TIMES
          ARE RESPECTED, THEY ARE NOT GUARANTEED. UNUSED TRANSFERS ARE NOT
          REFUNDABLE AND ALTERNATIVE TRANSPORT COSTS WILL NOT BE REIMBURSED
          UNLESS PRE-AUTHORIZED BY A CUSTOMER SERVICE CENTER MEMBER OF OUR TEAM.
          IF AUTHORIZED TO TAKE ALTERNATIVE TRANSPORT, PLEASE ENSURE THAT YOU
          OBTAIN A RECEIPT AND SUBMIT IT TO OUR CUSTOMER SERVICE CENTER FOR
          REVIEW. NO PAYMENT WILL BE DUE FOR TRAVEL EXPENSE CLAIMS SUBMITTED
          WITHOUT VALID RECEIPTS. FOR ARRIVAL TRANSFERS, OUR DRIVERS WILL WAIT
          FOR YOU UPON ARRIVAL UNTIL A MAXIMUM OF 90 MINUTES AFTER YOUR LANDING
          TIME. UPON DEPARTURE, OUR DRIVERS WILL WAIT BY THE PICK-UP POINT A
          MAXIMUM OF 20 MINUTES AFTER THE PUBLISHED PICK-UP TIME. IF YOU REQUEST
          THE DRIVER TO WAIT BEYOND THOSE 20 MINUTES, PLEASE NOTE THAT A WAITING
          FEE MIGHT BE CHARGED DIRECTLY BY THE DRIVER. YOU ARE RESPONSIBLE FOR
          CHECKING THE AGREED PICKUP TIME AND FOR ENSURING THAT THE RESULTING
          ARRIVAL TIME AT THE AIRPORT DEPARTURE TERMINAL IS AT LEAST 10 MINUTES
          BEFORE THE CHECK-IN DESK OPENS (NOT CLOSES) AND UNDER NO CIRCUMSTANCES
          LESS THAN TWO HOURS PRIOR TO THE SCHEDULED FLIGHT DEPARTURE TIME. THE
          DRIVER WILL PICK YOU UP AND SET YOU DOWN AS CLOSE AS POSSIBLE TO THE
          GIVEN ADDRESSES. IN THE EVENT THAT ACCESS VIA A CONVENTIONAL ROUTE IS
          CLOSED DUE TO WEATHER CONDITIONS, ROAD ACCIDENTS, ETC., THE DRIVER
          WILL, AT YOUR EXPRESS REQUEST, USE A LONGER ROUTE TO REACH THE AGREED
          DESTINATION, BUT IN SUCH INSTANCES, YOU MAY BE LIABLE FOR ANY
          ADDITIONAL COSTS. WHILST WE ENDEAVOR TO PROVIDE SMS CONFIRMATION
          MESSAGES, THIS SERVICE IS DEPENDENT UPON TELEPHONE NETWORKS THAT ARE
          BEYOND OUR CONTROL. IF A TEXT MESSAGE IS LOST OR DELAYED THE CUSTOMER
          SHALL REFER TO THE INFORMATION PROVIDED BY EMAIL OR IN THE ‘YOUR
          BOOKINGS’ SECTION OF OUR WEBSITE.
        </p>

        <h3 className={styles.subTitle}>Company Details</h3>
        <li className={styles.listItems}>
          Website: <a href="www.msluxurymotors.com">www.msluxurymotors.com</a>
        </li>
        <li className={styles.listItems}>Owned by: MS Luxury Motors Ltd.</li>
        <li className={styles.listItems}>
          Address: 123 Main Street, Cityville, Country, 12345
        </li>
        <li className={styles.listItems}>Contact Number: +123 (456) 7890</li>
      </Box>
    </Layout>
  );
};

export default TermsAndConditions;
